name: Release

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main # Adjusted from 'master' based on your previous logs

jobs:
  release:
    name: Release
    permissions:
      contents: write    # To create tags and releases
      id-token: write    # To sign the build (Provenance)
      attestations: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.x
          cache: true

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3
        with:
          build-root-directory: ${{ github.workspace }}/android

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Generate code files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Setup keystore
        # This decodes your secret and creates the physical file needed to sign the APK
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > "android/app/keystore.jks"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: main
          # We manually list plugins to skip @semantic-release/npm (avoiding the ENOPKG error)
          plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github

      - name: Build Signed APK
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          flutter build apk --release \
            --dart-define=KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
            --dart-define=KEYSTORE_ALIAS=${{ secrets.KEYSTORE_ENTRY_ALIAS }} \
            --dart-define=KEYSTORE_ALIAS_PASSWORD=${{ secrets.KEYSTORE_ENTRY_PASSWORD }}

      - name: Upload Binaries to GitHub Release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.semantic.outputs.new_release_version }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest (Provenance)
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: build/app/outputs/flutter-apk/app-release.apk
